name: GH-Pages

on:
  push:
    branches: [ main ]

jobs:

  build:
    name: Build Flutter Web
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
  
  deploy:
    needs: [build]
    name: Deploy on GitHub pages
    runs-on: ubuntu-latest
    
    steps:
      - uses: erickzanardo/flutter-gh-pages@v3
