name: GH-Pages

on:
  push:
    branches: [ main ]

jobs:

  build:
    name: Build Flutter Web and Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - uses: erickzanardo/flutter-gh-pages@v3
